version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redischat-redis
    profiles: ["local"]
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redischat-web
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      # Use external Upstash by setting REDIS_CONNECTION_STRING env (StackExchange.Redis format)
      # Example: open-adder-8344.upstash.io:6379,password=***,ssl=True,abortConnect=false
      - Redis__ConnectionString=${REDIS_CONNECTION_STRING:-redis:6379,abortConnect=false}
      - ConnectionStrings__Default=Data Source=/data/chat.db
    ports:
      - "8080:8080"
    volumes:
      - app-data:/data

volumes:
  redis-data:
  app-data:
